'use client';

// import type { Metadata } from 'next';
// import AuthLayout from './(auth)/login/layout';
// import { Nunito, Geist, Geist_Mono } from 'next/font/google';
import { Providers } from './providers';
import { Nunito } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { Navbar } from '@/components/shared/navbar';

// Configure the Nunito font
const nunito = Nunito({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-nunito', // This links the font to a CSS variable
  weight: ['300', '400', '600', '700', '900'], // Choose the weights you need
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={cn('h-full', 'antialiased', nunito.variable)}>
      <body className='min-h-full flex flex-col font-sans'>
        {/* <body className={`${nunito.variable} font-sans antialiased`}> */}
        {/* <AuthLayout> */}
        {/* <main className='custom-container mx-auto w-full  flex-1 px-4'> */}
        <Providers>
          <Navbar />

          <main className='mx-auto w-full flex-1 px-4'>{children}</main>
          {/* </AuthLayout> */}
        </Providers>
      </body>
    </html>
  );
}
