'use client';

// import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import Providers from './providers';
import { Navbar } from '@/components/shared/navbar/Navbar';
import { Footer } from '@/components/shared/footer/Footer';
// Configure the Nunito font
const nunito = Nunito({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-nunito', // This links the font to a CSS variable
  weight: ['300', '400', '600', '700', '900'], // Choose the weights you need
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={cn('h-full', 'antialiased', nunito.variable)}>
      <body className='min-h-full flex flex-col font-sans'>
        <Providers>
          <Navbar />

          <main className='mx-auto w-full flex-1 px-4'>{children}</main>

          <Footer />
        </Providers>
      </body>
    </html>
  );
}
